repos:
  - repo: local
    hooks:
      - id: regression-suite
        name: Regression Suite
        entry: ./tests/run.sh
        language: system
        pass_filenames: false
  - repo: https://github.com/nip-was-here/pre-commit-license-header
    rev: 265e5b5ccf92377e63ef39cbe87d38181dabe5e7
    hooks:
      - id: license-header
        name: License Header
        language: python
        files: ^(\/?[^\.]+\/)*[^\.\/]+\.[^\/]+$
        args: [
          "-e", "README.md",
          "-e", "doc/*",
          "-e", "doc/**/*",
          "--template", ".license-header",
          "--copyright-holder", "nip"
        ]
  - repo: https://github.com/nip-was-here/pre-commit-adr-toc
    rev: 1.0.0
    hooks:
      - id: adr-toc
        name: ADR Table of Content
        language: unsupported_script
        entry: adr-toc.sh
        pass_filenames: false
        files: '^doc/adr/(?!README\.md$).*\.md$'
