#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 nip
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)/tests/support/shell-test.sh"

output="$({
  pidev_nvim_output \
    +"lua require('pi-dev').setup({ keymaps = { enable = false }, ui = { width = 80, input_height = 8 } })" \
    +"lua local events = require('pi-dev.events'); local state = require('pi-dev.state'); local statusline = require('pi-dev.statusline'); assert(statusline.short_status_label('running') == 'run'); assert(statusline.short_status_label('waiting input') == 'wait'); assert(statusline.short_status_label('loading') == 'load'); assert(statusline.short_status_label('not connected') == 'off'); assert(statusline.short_status_label('compacting') == 'compact'); assert(statusline.short_status_label('retrying') == 'retry'); assert(statusline.short_status_label('error') == 'err'); assert(statusline.render_for_width(80):find('Pi status: off', 1, true), statusline.render_for_width(80)); events.emit('*', { type = 'start' }); assert(statusline.render_for_width(80):find('Pi status: idle', 1, true), statusline.render_for_width(80)); events.emit('*', { type = 'agent_start' }); events.emit('*', { type = 'extension_ui_request', method = 'select' }); assert(state.statusline.status == 'waiting input', state.statusline.status); assert(statusline.render_for_width(80):find('Pi status: wait', 1, true), statusline.render_for_width(80)); events.emit('*', { type = 'agent_end' }); assert(state.statusline.status == 'idle'); events.emit('*', { type = 'exit' }); assert(statusline.render_for_width(80):find('Pi status: off', 1, true), statusline.render_for_width(80))" \
    +"lua local statusline = require('pi-dev.statusline'); statusline.update_from_state({ model = { provider = 'anthropic', id = 'claude-sonnet-4' }, thinkingLevel = 'high', isStreaming = false }); statusline.update_from_stats({ cost = 0.125, tokens = { total = 12345 }, contextUsage = { tokens = 50000, contextWindow = 200000, percent = 25 } }); local line = statusline.render_for_width(120); assert(line:sub(1, 2) ~= '> ', line); assert(line:find('Pi status:', 1, true), line); assert(line:find('anthropic/claude-sonnet-4', 1, true), line); assert(line:find('think high', 1, true) == nil, line); assert(line:find('ctx 25%', 1, true), line); assert(line:find('12.3k tok', 1, true), line); assert(line:find('0.13', 1, true), line); statusline.update_from_state({ model = { provider = 'openai', modelId = 'o3' }, reasoningLevel = 'medium', isStreaming = false }); line = statusline.render_for_width(120); assert(line:sub(1, 2) ~= '> ', line); assert(line:find('openai/o3', 1, true), line); assert(line:find('think medium', 1, true) == nil, line)" \
    +"lua local statusline = require('pi-dev.statusline'); local events = require('pi-dev.events'); local ui = require('pi-dev.ui'); local state = require('pi-dev.state'); ui.show(); local long_error = 'Model not found: fake/broken with a very long provider response that must be truncated before metrics are pushed out of the status line'; statusline.update_from_stats({ tokens = { total = 1234 } }); statusline.set_error(long_error); local line = statusline.render_for_width(60); assert(line:find('Pi status: err ', 1, true), line); assert(vim.fn.strdisplaywidth(line) <= 60, line); assert(line:find('...', 1, true), line); local text = table.concat(vim.api.nvim_buf_get_lines(state.ui.output_buf, 0, -1, false), '\n'); assert(text:find('> Error: Model not found: fake/broken', 1, true), text); events.emit('*', { type = 'message_start', message = { role = 'user', content = 'continue' } }); line = statusline.render_for_width(120); assert(line:find('Model not found', 1, true) == nil, line); statusline.set_error('Another stale error'); events.emit('*', { type = 'agent_start' }); line = statusline.render_for_width(120); assert(line:find('Another stale error', 1, true) == nil, line); assert(line:find('Pi status: run', 1, true), line); events.emit('*', { type = 'compaction_start' }); line = statusline.render_for_width(120); assert(line:find('Pi status: compact', 1, true), line); events.emit('*', { type = 'compaction_end', reason = 'threshold' }); line = statusline.render_for_width(120); assert(line:find('Pi status: run', 1, true), line); assert(line:find('compacting', 1, true) == nil, line); events.emit('*', { type = 'auto_retry_start' }); line = statusline.render_for_width(120); assert(line:find('Pi status: retry', 1, true), line); events.emit('*', { type = 'auto_retry_end' }); line = statusline.render_for_width(120); assert(line:find('Pi status: run', 1, true), line); events.emit('*', { type = 'agent_end' }); statusline.update_from_state({ isCompacting = true }); assert(statusline.render_for_width(120):find('Pi status: compact', 1, true)); statusline.update_from_state({ isCompacting = false, isStreaming = false }); line = statusline.render_for_width(120); assert(line:find('Pi status: off', 1, true), line)" \
    +"lua local ui = require('pi-dev.ui'); ui.show_interaction({ title = 'Pi permission', items = { { label = 'Yes' }, { label = 'No' } } }); local state = require('pi-dev.state'); assert(vim.bo[state.ui.interaction_buf].modifiable == false, 'permission/select interaction buffer must be non-modifiable'); assert(vim.bo[state.ui.input_buf].modifiable == true, 'draft Pi input buffer should remain editable behind interaction')"
} 2>&1)" || {
  printf '%s\n' "$output"
  exit 1
}

pidev_assert_no_nvim_errors "$output"
